# Generated by Django 3.1 on 2024-06-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=70)),
                ('student_email', models.EmailField(max_length=70)),
                ('student_password', models.CharField(max_length=70)),
            ],
        ),
    ]
