# Generated by Django 3.1 on 2024-06-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studid', models.IntegerField()),
                ('stuname', models.CharField(max_length=30)),
                ('stuemail', models.EmailField(max_length=254)),
                ('stupass', models.CharField(max_length=30)),
            ],
        ),
    ]
