# Generated by Django 3.1 on 2024-06-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='common',
            field=models.CharField(default='common', max_length=30),
        ),
    ]
